-- Thai names for menu data. Safe to run once on an existing database (D1: wrangler d1 execute DB --remote --file=db/migrations/0002_thai_names.sql).
alter table categories add column name_th text;
alter table menu_items add column name_th text;
alter table menu_items add column description_th text;
alter table option_groups add column name_th text;
alter table option_choices add column name_th text;
update categories set name_th = 'เบอร์เกอร์' where name = 'Burgers' and name_th is null;
update categories set name_th = 'พิซซ่า' where name = 'Pizza' and name_th is null;
update categories set name_th = 'ไรซ์โบวล์' where name = 'Bowls' and name_th is null;
update categories set name_th = 'เมนูเคียง' where name = 'Sides' and name_th is null;
update categories set name_th = 'เครื่องดื่ม' where name = 'Drinks' and name_th is null;
update categories set name_th = 'ของหวาน' where name = 'Desserts' and name_th is null;
update menu_items set name_th = 'สแมชเบอร์เกอร์', description_th = 'เนื้อคู่ ชีสเชดดาร์ แตงกวาดอง ซอสสูตรพิเศษ' where name = 'Smash Burger' and name_th is null;
update menu_items set name_th = 'ไก่กรอบ', description_th = 'สะโพกไก่ชุบบัตเตอร์มิลค์ โคลสลอว์ ซอสฮอตฮันนี่' where name = 'Crispy Chicken' and name_th is null;
update menu_items set name_th = 'เห็ดชีสเยิ้ม', description_th = 'เห็ดพอร์โทเบลโล ชีสกรูแยร์ หอมใหญ่คาราเมล' where name = 'Mushroom Melt' and name_th is null;
update menu_items set name_th = 'มาร์เกอริต้า', description_th = 'ซอสมะเขือเทศ ชีสฟิออร์ดิลัตเต้ ใบโหระพา' where name = 'Margherita' and name_th is null;
update menu_items set name_th = 'เปปเปอโรนี', description_th = 'เปปเปอโรนีหน้าถ้วย ออริกาโน น้ำมันพริก' where name = 'Pepperoni' and name_th is null;
update menu_items set name_th = 'โฟร์ชีส', description_th = 'มอสซาเรลลา กอร์กอนโซลา ฟอนตินา พาร์เมซาน' where name = 'Four Cheese' and name_th is null;
update menu_items set name_th = 'ข้าวแซลมอนเทริยากิ', description_th = 'ข้าว ถั่วแระญี่ปุ่น ขิงดอง' where name = 'Teriyaki Salmon' and name_th is null;
update menu_items set name_th = 'ฟาลาเฟลโบวล์', description_th = 'ฮัมมัส ทับบูเลห์ ทาฮีนี' where name = 'Falafel Bowl' and name_th is null;
update menu_items set name_th = 'เฟรนช์ฟรายส์', description_th = 'เกลือทะเล อายโอลี' where name = 'Fries' and name_th is null;
update menu_items set name_th = 'หอมทอดวงแหวน', description_th = 'แป้งเบียร์ มายองเนสชิโปเทล' where name = 'Onion Rings' and name_th is null;
update menu_items set name_th = 'ซีซาร์สลัด', description_th = 'ผักโรเมน ขนมปังกรอบ พาร์เมซาน' where name = 'Caesar Salad' and name_th is null;
update menu_items set name_th = 'เลมอนเนด', description_th = 'คั้นสด ใบสะระแหน่' where name = 'Lemonade' and name_th is null;
update menu_items set name_th = 'ชาเย็น', description_th = 'ชาดำ นมข้นหวาน' where name = 'Thai Iced Tea' and name_th is null;
update menu_items set name_th = 'โคล่า', description_th = 'กระป๋อง 330 มล.' where name = 'Cola' and name_th is null;
update menu_items set name_th = 'บราวนี่ช็อกโกแลต', description_th = 'เสิร์ฟร้อน พร้อมไอศกรีมวานิลลา' where name = 'Chocolate Brownie' and name_th is null;
update menu_items set name_th = 'ซันเดย์', description_th = 'ซอฟต์เสิร์ฟ คาราเมล ถั่วลิสง' where name = 'Sundae' and name_th is null;
update option_groups set name_th = 'ท็อปปิ้งเพิ่ม' where name = 'Add-ons' and name_th is null;
update option_groups set name_th = 'ความสุก' where name = 'Doneness' and name_th is null;
update option_groups set name_th = 'ขนาด' where name = 'Size' and name_th is null;
update option_groups set name_th = 'ระดับความหวาน' where name = 'Sweetness' and name_th is null;
update option_choices set name_th = 'ชีสเพิ่ม' where name = 'Extra cheese' and name_th is null;
update option_choices set name_th = 'เบคอน' where name = 'Bacon' and name_th is null;
update option_choices set name_th = 'ไข่ดาว' where name = 'Fried egg' and name_th is null;
update option_choices set name_th = 'สุกปานกลาง' where name = 'Medium' and name_th is null;
update option_choices set name_th = 'ค่อนข้างสุก' where name = 'Medium well' and name_th is null;
update option_choices set name_th = 'สุกมาก' where name = 'Well done' and name_th is null;
update option_choices set name_th = 'ปกติ 10 นิ้ว' where name = 'Regular 10"' and name_th is null;
update option_choices set name_th = 'ใหญ่ 14 นิ้ว' where name = 'Large 14"' and name_th is null;
update option_choices set name_th = 'ไม่ใส่น้ำตาล' where name = 'No sugar' and name_th is null;
