-- Restaurant POS schema for Cloudflare D1 (SQLite). Idempotent: safe to re-run.
-- Conventions: ids are UUID text (generated by the app; the 32-hex default is only a fallback for manual inserts),
-- money is REAL rounded to 2 dp by the app, booleans are 0/1, timestamps are ISO-8601 UTC text.

create table if not exists companies (
  id text primary key default (lower(hex(randomblob(16)))),
  name text not null,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists branches (
  id text primary key default (lower(hex(randomblob(16)))),
  company_id text not null references companies(id),
  name text not null,
  address text,
  phone text,
  timezone text not null default 'Asia/Bangkok',
  currency text not null default 'THB',
  tax_rate real not null default 7 check (tax_rate >= 0),
  service_charge_rate real not null default 0 check (service_charge_rate >= 0),
  is_active integer not null default 1 check (is_active in (0,1)),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists staff (
  id text primary key default (lower(hex(randomblob(16)))),
  company_id text not null references companies(id),
  branch_id text references branches(id),
  full_name text not null,
  email text,
  password_hash text,
  role text not null check (role in ('admin','kitchen','cashier','customer')),
  pin_code_hash text,
  is_active integer not null default 1 check (is_active in (0,1)),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
create unique index if not exists staff_email_idx on staff (lower(email));

create table if not exists sessions (
  id text primary key,
  staff_id text not null references staff(id) on delete cascade,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  expires_at text not null
);
create index if not exists sessions_staff_idx on sessions (staff_id);

create table if not exists categories (
  id text primary key default (lower(hex(randomblob(16)))),
  company_id text not null references companies(id),
  name text not null,
  name_th text,
  sort_order integer not null default 0,
  is_active integer not null default 1 check (is_active in (0,1)),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists menu_items (
  id text primary key default (lower(hex(randomblob(16)))),
  company_id text not null references companies(id),
  category_id text not null references categories(id),
  name text not null,
  name_th text,
  description text,
  description_th text,
  base_price real not null check (base_price >= 0),
  image_url text,
  is_available integer not null default 1 check (is_available in (0,1)),
  sort_order integer not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists menu_item_images (
  id text primary key default (lower(hex(randomblob(16)))),
  menu_item_id text not null references menu_items(id),
  content_type text not null default 'image/jpeg',
  data_b64 text not null,
  size_bytes integer not null default 0,
  sort_order integer not null default 0,
  is_primary integer not null default 0 check (is_primary in (0,1)),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists menu_item_branch_overrides (
  id text primary key default (lower(hex(randomblob(16)))),
  menu_item_id text not null references menu_items(id),
  branch_id text not null references branches(id),
  price real check (price >= 0),
  is_available integer check (is_available in (0,1))
);

create table if not exists option_groups (
  id text primary key default (lower(hex(randomblob(16)))),
  menu_item_id text not null references menu_items(id),
  name text not null,
  name_th text,
  selection_type text not null check (selection_type in ('single','multiple')),
  is_required integer not null default 0 check (is_required in (0,1)),
  min_select integer not null default 0,
  max_select integer,
  sort_order integer not null default 0
);

create table if not exists option_choices (
  id text primary key default (lower(hex(randomblob(16)))),
  option_group_id text not null references option_groups(id),
  name text not null,
  name_th text,
  price_delta real not null default 0,
  is_available integer not null default 1 check (is_available in (0,1)),
  sort_order integer not null default 0
);

create table if not exists dining_tables (
  id text primary key default (lower(hex(randomblob(16)))),
  branch_id text not null references branches(id),
  name text not null,
  zone text,
  seats integer not null default 4,
  status text not null default 'available' check (status in ('available','occupied','reserved','cleaning')),
  pos_x real,
  pos_y real,
  width real not null default 120,
  height real not null default 96,
  shape text not null default 'rect' check (shape in ('round','rect')),
  is_active integer not null default 1 check (is_active in (0,1)),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists orders (
  id text primary key default (lower(hex(randomblob(16)))),
  branch_id text not null references branches(id),
  table_id text references dining_tables(id),
  order_number text not null,
  order_type text not null check (order_type in ('dine_in','takeaway','delivery')),
  status text not null default 'open' check (status in ('open','sent_to_kitchen','ready','served','completed','cancelled')),
  opened_by_staff_id text references staff(id),
  customer_name text,
  customer_count integer,
  subtotal real not null default 0,
  discount_total real not null default 0,
  tax_total real not null default 0,
  service_charge_total real not null default 0,
  tip_total real not null default 0,
  grand_total real not null default 0,
  notes text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  closed_at text
);

create table if not exists order_items (
  id text primary key default (lower(hex(randomblob(16)))),
  order_id text not null references orders(id),
  menu_item_id text not null references menu_items(id),
  item_name text not null,
  unit_price real not null,
  quantity integer not null check (quantity > 0),
  status text not null default 'pending' check (status in ('pending','preparing','ready','served','cancelled')),
  notes text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists order_item_options (
  id text primary key default (lower(hex(randomblob(16)))),
  order_item_id text not null references order_items(id),
  option_choice_id text references option_choices(id),
  choice_name text not null,
  price_delta real not null default 0
);

create table if not exists discounts (
  id text primary key default (lower(hex(randomblob(16)))),
  company_id text not null references companies(id),
  name text not null,
  type text not null check (type in ('percentage','fixed')),
  value real not null check (value >= 0),
  is_active integer not null default 1 check (is_active in (0,1))
);

create table if not exists order_discounts (
  id text primary key default (lower(hex(randomblob(16)))),
  order_id text not null references orders(id),
  discount_id text references discounts(id),
  label text not null,
  amount real not null check (amount >= 0),
  applied_by_staff_id text references staff(id),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists payments (
  id text primary key default (lower(hex(randomblob(16)))),
  order_id text not null references orders(id),
  method text not null check (method in ('cash','card','qr_promptpay','other')),
  amount real not null check (amount >= 0),
  received_amount real,
  change_amount real,
  status text not null default 'completed' check (status in ('pending','completed','refunded')),
  staff_id text references staff(id),
  paid_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists receipts (
  id text primary key default (lower(hex(randomblob(16)))),
  order_id text not null references orders(id),
  receipt_number text not null unique,
  snapshot text not null,
  printed_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  reprint_count integer not null default 0
);

create table if not exists inventory_items (
  id text primary key default (lower(hex(randomblob(16)))),
  branch_id text not null references branches(id),
  name text not null,
  unit text not null,
  quantity_on_hand real not null default 0,
  reorder_threshold real not null default 0,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists menu_item_ingredients (
  id text primary key default (lower(hex(randomblob(16)))),
  menu_item_id text not null references menu_items(id),
  inventory_item_id text not null references inventory_items(id),
  quantity_used real not null check (quantity_used > 0)
);

create table if not exists inventory_transactions (
  id text primary key default (lower(hex(randomblob(16)))),
  inventory_item_id text not null references inventory_items(id),
  order_item_id text references order_items(id),
  change_qty real not null,
  reason text not null check (reason in ('sale','restock','adjustment','waste')),
  staff_id text references staff(id),
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

create table if not exists audit_logs (
  id text primary key default (lower(hex(randomblob(16)))),
  company_id text not null references companies(id),
  staff_id text references staff(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  old_value text,
  new_value text,
  created_at text not null default (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Note: updated_at has no trigger (D1's REST endpoint can't apply trigger bodies); the app sets it on update.

-- Indexes
create index if not exists branches_company_idx on branches (company_id);
create index if not exists staff_company_idx on staff (company_id);
create index if not exists categories_company_idx on categories (company_id);
create index if not exists menu_items_company_idx on menu_items (company_id, category_id);
create index if not exists overrides_item_branch_idx on menu_item_branch_overrides (menu_item_id, branch_id);
create index if not exists option_groups_item_idx on option_groups (menu_item_id);
create index if not exists option_choices_group_idx on option_choices (option_group_id);
create index if not exists dining_tables_branch_idx on dining_tables (branch_id);
create unique index if not exists orders_branch_number_idx on orders (branch_id, order_number);
create index if not exists orders_branch_status_idx on orders (branch_id, status);
create index if not exists orders_table_idx on orders (table_id);
create index if not exists order_items_order_idx on order_items (order_id);
create index if not exists order_items_status_idx on order_items (status);
create index if not exists order_item_options_item_idx on order_item_options (order_item_id);
create index if not exists payments_order_idx on payments (order_id);
create index if not exists receipts_order_idx on receipts (order_id);
create index if not exists menu_item_images_item_idx on menu_item_images (menu_item_id, sort_order);
create unique index if not exists menu_item_images_primary_idx on menu_item_images (menu_item_id) where is_primary = 1;
